# Generated by Django 3.0.4 on 2020-03-31 05:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_trip_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('data_inicio', 'data_fim', 'user_id')},
        ),
    ]
